#!/bin/sh

# Fail on error
set -e

export LAMBDA_TASK_ROOT=/var/app

while true
do
    # We redirect stderr to stdout so that everything
    # written on the output ends up in Cloudwatch automatically
    php bootstrap.php 2>&1
done
